### ISSUE TITLE
error in EKS

### ISSUE THREAD

**Issue by chaishiqi** [k8spacket/k8spacket#56]
EKS version：1.27
helm version: v3.14.1

helm install k8spacket --namespace k8spacket k8spacket/k8spacket --create-namespace

After executing command,  k8spacket agent back-off restarting failed, here is the log

```
2024/06/10 17:37:34 [k8spacket] [plugins] Cannot find plugin TLSConsumerPlugin, gave up. plugin: symbol TLSConsumerPlugin not found in plugin github.com/k8spacket/plugins/nodegraph
2024/06/10 17:37:34 [k8spacket] [plugins] Cannot find plugin TCPConsumerPlugin, gave up. plugin: symbol TCPConsumerPlugin not found in plugin github.com/k8spacket/plugins/tls-parser
2024/06/10 17:37:34 [k8spacket] [api] Serving requests on port 6676
2024/06/10 17:37:34 [k8spacket] INIT inet
2024/06/10 17:37:34 [k8spacket] [inet] Cannot attach tracepoint: neither debugfs nor tracefs are mounted
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1f5320f]

goroutine 12 [running]:
github.com/k8spacket/k8spacket/ebpf/inet.Init()
	/home/k8spacket/ebpf/inet/inet.go:54 +0x1cf
created by github.com/k8spacket/k8spacket/ebpf.LoadEbpf in goroutine 1
	/home/k8spacket/ebpf/loader.go:20 +0x1a
```

how to avoid it？

**Comment by bareckidarek** [comment]
Hi @chaishiqi 

See: https://github.com/k8spacket/k8spacket/issues/55#issuecomment-2149796549

**Comment by k8spacket** [comment]
Hi @chaishiqi 

I hope you found the solution.
This thread has been inactive for 10 days. I'm going to close it. 
Feel free to reopen if you have more questions.
